version: "3.8"
services:
  TasksManagementSystems:
    image: tasksmanagement
    restart: on-failure
    ports:
      - "8082:8082"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATA_SOURCE: jdbc:mysql://db:3306/TasksSystem
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: rootuser


  db:
    image: mysql:8.0.33
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: TasksSystem
      MYSQL_ROOT_PASSWORD: rootuser





